# Generated by Django 3.1.6 on 2022-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eventname', models.CharField(blank=True, max_length=200, null=True)),
                ('adobe', models.CharField(blank=True, max_length=200, null=True)),
                ('record', models.TextField(blank=True, null=True)),
                ('hero', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('export_pdf', models.BooleanField(default=False)),
                ('fileupload', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
